using System.Text;

namespace Eidosc.Ide;

public static class GeneratedDocumentRenderer
{
    public static IdeGeneratedDocumentEntry Create(IdeSymbolEntry symbol)
    {
        ArgumentNullException.ThrowIfNull(symbol);
        var origin = symbol.GeneratedOrigin ??
                     throw new ArgumentException("Symbol does not have a generated origin.", nameof(symbol));
        return new IdeGeneratedDocumentEntry
        {
            Uri = origin.VirtualDocumentPath,
            LanguageId = "eidos",
            StableIdentity = origin.StableIdentity,
            GeneratorIdentity = origin.GeneratorIdentity,
            TargetIdentity = origin.TargetIdentity,
            Content = Render(symbol)
        };
    }

    public static string Render(IdeSymbolEntry symbol)
    {
        ArgumentNullException.ThrowIfNull(symbol);
        var origin = symbol.GeneratedOrigin ??
                     throw new ArgumentException("Symbol does not have a generated origin.", nameof(symbol));
        var builder = new StringBuilder();
        builder.Append(symbol.Name);
        if (!string.IsNullOrWhiteSpace(symbol.GenericParameterText))
        {
            builder.Append(symbol.GenericParameterText);
        }

        builder.Append(" :: ");
        builder.Append(SelectDeclarationSurface(symbol));
        builder.AppendLine(";");
        builder.AppendLine();
        builder.AppendLine($"// generated by {origin.GeneratorIdentity}");
        builder.AppendLine($"// target {origin.TargetIdentity}");
        builder.AppendLine($"// stable identity {origin.StableIdentity}");
        builder.AppendLine($"// attribute occurrence {origin.AttributeOccurrenceIndex}, expansion output {origin.ExpansionOutputIndex}");
        builder.AppendLine($"// canonical arguments {origin.CanonicalArgumentsHash}");
        builder.AppendLine($"// Meta schema {origin.MetaSchemaVersion}");
        return builder.ToString();
    }

    private static string SelectDeclarationSurface(IdeSymbolEntry symbol)
    {
        if (!string.IsNullOrWhiteSpace(symbol.TypeText))
        {
            return symbol.TypeText;
        }

        if (!string.IsNullOrWhiteSpace(symbol.Detail))
        {
            return symbol.Detail;
        }

        return symbol.Kind;
    }
}
