using System.Text;

namespace Eidosc.Ide;

public static class GeneratedDocumentRenderer
{
    public static IdeGeneratedDocumentEntry Create(IdeSymbolEntry symbol)
        => Create([symbol]);

    public static IdeGeneratedDocumentEntry Create(IReadOnlyList<IdeSymbolEntry> symbols)
        => Create(symbols, new Dictionary<int, string>());

    internal static IdeGeneratedDocumentEntry Create(
        IReadOnlyList<IdeSymbolEntry> symbols,
        IReadOnlyDictionary<int, string> generatedFunctionBodies)
    {
        ArgumentNullException.ThrowIfNull(symbols);
        ArgumentNullException.ThrowIfNull(generatedFunctionBodies);
        if (symbols.Count == 0)
        {
            throw new ArgumentException("At least one generated symbol is required.", nameof(symbols));
        }

        var origin = symbols[0].GeneratedOrigin ??
                     throw new ArgumentException("Symbol does not have a generated origin.", nameof(symbols));
        if (symbols.Any(symbol => symbol.GeneratedOrigin?.VirtualDocumentPath != origin.VirtualDocumentPath))
        {
            throw new ArgumentException("Generated symbols must share one virtual document.", nameof(symbols));
        }

        return new IdeGeneratedDocumentEntry
        {
            Uri = origin.VirtualDocumentPath,
            LanguageId = "eidos",
            StableIdentity = origin.StableIdentity,
            GeneratorIdentity = origin.GeneratorIdentity,
            TargetIdentity = origin.TargetIdentity,
            Content = Render(symbols, generatedFunctionBodies)
        };
    }

    public static string Render(IdeSymbolEntry symbol)
        => Render([symbol]);

    public static string Render(IReadOnlyList<IdeSymbolEntry> symbols)
        => Render(symbols, new Dictionary<int, string>());

    internal static string Render(
        IReadOnlyList<IdeSymbolEntry> symbols,
        IReadOnlyDictionary<int, string> generatedFunctionBodies)
    {
        ArgumentNullException.ThrowIfNull(symbols);
        ArgumentNullException.ThrowIfNull(generatedFunctionBodies);
        if (symbols.Count == 0)
        {
            throw new ArgumentException("At least one generated symbol is required.", nameof(symbols));
        }

        var origin = symbols[0].GeneratedOrigin ??
                     throw new ArgumentException("Symbol does not have a generated origin.", nameof(symbols));
        var builder = new StringBuilder();
        foreach (var symbol in symbols
                     .OrderBy(static symbol => symbol.Kind == "impl" ? 0 : 1)
                     .ThenBy(static symbol => symbol.Name, StringComparer.Ordinal))
        {
            AppendDeclarationSurface(builder, symbol, generatedFunctionBodies);
        }
        builder.AppendLine();
        builder.AppendLine($"// generated by {origin.GeneratorIdentity}");
        builder.AppendLine($"// target {origin.TargetIdentity}");
        builder.AppendLine($"// stable identity {origin.StableIdentity}");
        builder.AppendLine($"// clause occurrence {origin.ClauseOccurrenceIndex}, expansion output {origin.ExpansionOutputIndex}");
        builder.AppendLine($"// clause occurrence {origin.ClauseOccurrenceIdentity}, argument {origin.ClauseArgumentSubIndex}");
        builder.AppendLine($"// canonical arguments {origin.CanonicalArgumentsHash}");
        builder.AppendLine($"// generation slot {origin.GenerationSlotIdentity}");
        builder.AppendLine($"// Meta schema {origin.MetaSchemaVersion}");
        return builder.ToString();
    }

    private static void AppendDeclarationSurface(
        StringBuilder builder,
        IdeSymbolEntry symbol,
        IReadOnlyDictionary<int, string> generatedFunctionBodies)
    {
        builder.Append(symbol.Name);
        if (!string.IsNullOrWhiteSpace(symbol.GenericParameterText))
        {
            builder.Append(symbol.GenericParameterText);
        }

        builder.Append(" :: ");
        builder.Append(SelectDeclarationSurface(symbol));
        if (generatedFunctionBodies.TryGetValue(symbol.SymbolId, out var body))
        {
            builder.AppendLine();
            builder.AppendLine(body);
            return;
        }

        builder.AppendLine(";");
    }

    private static string SelectDeclarationSurface(IdeSymbolEntry symbol)
    {
        if (!string.IsNullOrWhiteSpace(symbol.TypeText))
        {
            return symbol.TypeText;
        }

        if (!string.IsNullOrWhiteSpace(symbol.Detail))
        {
            return symbol.Detail;
        }

        return symbol.Kind;
    }
}
