using System.Text;

namespace Eidosc.Bindgen;

/// <summary>
/// 自动 C shim 生成（P0 M4/M5）。
/// 规则：
/// 1. struct 按值参数 → <c>void*</c> 参数 + 解引用转发；
/// 2. struct 按值返回 → 静态槽 + 指针返回 shim（Eidos 侧 <c>RawPtr</c>，不可重入）；
/// 3. 窄标量（非 64 位整数、<c>float</c>、enum）→ <c>int64_t</c>/<c>double</c> 参数/返回 +
///    C 类型转换（当前 Eidos MIR/backend 边界只支持 64 位标量，E5337）；
/// 4. 其余 ABI 形态（变参、捕获回调）保持 SKIP（生成器不产出危险转发）。
/// </summary>
public sealed class BindingCShimGenerator
{
    private readonly CHeaderIr _ir;
    private readonly BindingTypeMapper _typeMapper;

    public BindingCShimGenerator(CHeaderIr ir)
    {
        _ir = ir;
        _typeMapper = new BindingTypeMapper(ir);
    }

    public bool HasShims => _ir.Functions.Any(NeedsShim);

    public string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by eidosc pkg bind. Do not edit this file directly.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine($"#include <stdint.h>");
        sb.AppendLine($"#include \"{Path.GetFileName(_ir.Header)}\"");
        sb.AppendLine();

        foreach (var fn in _ir.Functions.Where(NeedsShim).OrderBy(static fn => fn.Name, StringComparer.Ordinal))
        {
            GenerateShim(sb, fn);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private bool NeedsShim(CBindingFunction fn) =>
        fn.Parameters.Any(parameter => NeedsShim(parameter.Type)) ||
        NeedsShim(fn.ReturnType);

    private bool NeedsShim(CBindingType type)
    {
        var mapping = _typeMapper.Map(type);
        return mapping.Category == BindingTypeCategory.StructByValue ||
               (type.Kind is CBindingTypeKind.Primitive or CBindingTypeKind.Enum && NeedsNarrowing(type));
    }

    /// <summary>
    /// 当前编译器 FFI 边界只支持 64 位标量（E5337）；窄标量（char/short/int/float/enum，
    /// 不含 64 位整数与 bool）必须经 shim 窄化。Size==0（简单模式）视为未知 → 不 shim。
    /// </summary>
    private bool NeedsNarrowing(CBindingType type) =>
        type.Size is not (0 or 8) &&
        !(type.Kind == CBindingTypeKind.Primitive && type.Name is "bool" or "_Bool");

    private void GenerateShim(StringBuilder sb, CBindingFunction fn)
    {
        if (_typeMapper.Map(fn.ReturnType).Category == BindingTypeCategory.StructByValue)
        {
            GenerateStaticSlotReturnShim(sb, fn);
            return;
        }

        GenerateScalarShim(sb, fn);
    }

    private void GenerateScalarShim(StringBuilder sb, CBindingFunction fn)
    {
        var shimName = $"eidos_shim_{fn.Name}";
        var returnNarrowing = IsNarrowing(fn.ReturnType);
        var shimReturnType = returnNarrowing ? WideScalarType(fn.ReturnType) : fn.ReturnType.Spelling;

        sb.Append($"{shimReturnType} {shimName}(");
        sb.Append(string.Join(", ", fn.Parameters.Select(FormatShimParameter)));
        sb.AppendLine(")");
        sb.AppendLine("{");
        if (returnNarrowing)
        {
            sb.Append($"    return ({WideScalarType(fn.ReturnType)}){fn.Name}(");
            sb.Append(string.Join(", ", fn.Parameters.Select(FormatShimArgument)));
            sb.AppendLine(");");
        }
        else
        {
            if (shimReturnType != "void")
                sb.Append("    return ");
            sb.Append($"{fn.Name}(");
            sb.Append(string.Join(", ", fn.Parameters.Select(FormatShimArgument)));
            sb.AppendLine(");");
        }

        sb.AppendLine("}");
    }

    private string FormatShimParameter(CBindingParameter parameter)
    {
        var type = parameter.Type;
        if (NeedsNarrowing(type))
            return $"{WideScalarType(type)} {parameter.Name}";

        return _typeMapper.Map(type).Category == BindingTypeCategory.StructByValue
            ? $"void *{parameter.Name}_ptr"
            : $"{type.Spelling} {parameter.Name}";
    }

    private string FormatShimArgument(CBindingParameter parameter)
    {
        var type = parameter.Type;
        if (NeedsNarrowing(type))
            return $"({type.Spelling}){parameter.Name}";

        return _typeMapper.Map(type).Category == BindingTypeCategory.StructByValue
            ? $"*({type.Spelling}*){parameter.Name}_ptr"
            : parameter.Name;
    }

    /// <summary>
    /// struct 按值返回：静态槽 + 指针返回。Eidos 侧绑定 <c>-> RawPtr</c>，
    /// 调用方在下次调用前复制字段（单静态槽，不可重入）。
    /// </summary>
    private void GenerateStaticSlotReturnShim(StringBuilder sb, CBindingFunction fn)
    {
        var shimName = $"eidos_shim_{fn.Name}";
        var returnType = fn.ReturnType.Spelling;

        sb.AppendLine($"// {fn.ReturnType.Name} returned by value through a single static slot;");
        sb.AppendLine($"// callers must copy the result before the next call to {shimName}.");
        sb.AppendLine($"static {returnType} {shimName}_result;");
        sb.Append($"{returnType}* {shimName}(");
        sb.Append(string.Join(", ", fn.Parameters.Select(FormatShimParameter)));
        sb.AppendLine(")");
        sb.AppendLine("{");
        sb.Append($"    {shimName}_result = {fn.Name}(");
        sb.Append(string.Join(", ", fn.Parameters.Select(FormatShimArgument)));
        sb.AppendLine(");");
        sb.AppendLine($"    return &{shimName}_result;");
        sb.AppendLine("}");
    }

    private bool IsNarrowing(CBindingType type) =>
        (type.Kind is CBindingTypeKind.Primitive or CBindingTypeKind.Enum) && NeedsNarrowing(type);

    /// <summary>
    /// 窄标量的 shim 侧宽类型：<c>float</c> → <c>double</c>；其余（整数/enum）→ <c>int64_t</c>。
    /// </summary>
    private static string WideScalarType(CBindingType type) =>
        type.Name == "float" ? "double" : "int64_t";
}
