using System.Text;

namespace Eidosc.Bindgen;

/// <summary>
/// 自动 C shim 生成（P0 M4/M5）。
/// 规则：
/// 1. struct 按值参数 → 字段拆分 shim（叶字段以原生位宽直连，enum 叶宽化为 <c>int64_t</c>；
///    调用侧用 C99 compound literal 组装；Eidos 侧签名与叶字段一一对应）；
/// 2. struct 按值返回 → 静态槽 + 指针返回 shim（Eidos 侧 <c>RawPtr</c>，不可重入；
///    读取字段需等 Eidosc 窄标量支持落地）；
/// 3. 仍映射为 64 位 Eidos 标量的窄 C 尺寸（enum、无布局事实残留）→
///    <c>int64_t</c>/<c>double</c> 参数/返回 + C 类型转换；char/short/int 与 float
///    已直接映射 Eidos 窄标量，原生位宽过边界，不再窄化；
/// 4. 其余 ABI 形态（变参、捕获回调、含 union/数组字段的 struct 参数）保持 SKIP。
/// </summary>
public sealed class BindingCShimGenerator
{
    private readonly CHeaderIr _ir;
    private readonly BindingTypeMapper _typeMapper;
    private readonly IReadOnlyDictionary<string, CBindingStruct> _structsByName;
    private readonly IReadOnlyDictionary<string, CBindingTypedef> _typedefs;
    private readonly BindingSpecDocument? _spec;

    public BindingCShimGenerator(CHeaderIr ir, BindingSpecDocument? spec = null)
    {
        _ir = ir;
        _spec = spec;
        _typeMapper = new BindingTypeMapper(ir);
        _structsByName = ir.Structs.ToDictionary(static st => st.Name, StringComparer.Ordinal);
        _typedefs = (ir.TypedefsSafe ?? [])
            .ToDictionary(static t => t.Name, StringComparer.Ordinal);
    }

    public bool HasShims =>
        _ir.Functions.Any(NeedsShim) ||
        (_spec?.Unions is { Length: > 0 }) ||
        _ir.UnionsSafe.Any(static u => !string.IsNullOrWhiteSpace(u.Name) && u.Size > 0 && u.Fields.Count > 0);

    public string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by eidosc pkg bind. Do not edit this file directly.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#include <stdint.h>");
        sb.AppendLine($"#include \"{Path.GetFileName(_ir.Header)}\"");
        sb.AppendLine();

        foreach (var fn in _ir.Functions.Where(NeedsShim).OrderBy(static fn => fn.Name, StringComparer.Ordinal))
        {
            GenerateShim(sb, fn);
            sb.AppendLine();
        }

        foreach (var u in _ir.UnionsSafe
                     .Where(static u => !string.IsNullOrWhiteSpace(u.Name) && u.Size > 0)
                     .OrderBy(static u => u.Name, StringComparer.Ordinal))
        {
            GenerateUnionAccessors(sb, u);
            sb.AppendLine();
        }

        GenerateTaggedUnionHelpers(sb);

        return sb.ToString();
    }

    /// <summary>
    /// tagged-union 桥接辅助（M4c）：宿主 struct 的标签字段读写（int64_t 宽化）与
    /// 有效负载字段取址。
    /// </summary>
    private void GenerateTaggedUnionHelpers(StringBuilder sb)
    {
        foreach (var rule in _spec?.Unions ?? [])
        {
            if (string.IsNullOrWhiteSpace(rule.Struct) ||
                !_structsByName.TryGetValue(rule.Struct!, out var hostStruct))
            {
                continue;
            }

            var structType = _typedefs.ContainsKey(hostStruct.Name) ? hostStruct.Name : $"struct {hostStruct.Name}";
            var tagField = hostStruct.Fields.FirstOrDefault(f => string.Equals(f.Name, rule.TagField, StringComparison.Ordinal));
            if (tagField != null)
            {
                var tagGet = RawBindingGenerator.StructFieldShimName(rule.Struct!, rule.TagField!, "get");
                var tagSet = RawBindingGenerator.StructFieldShimName(rule.Struct!, rule.TagField!, "set");
                sb.AppendLine($"int64_t {tagGet}(void* p) {{ return (int64_t)(({structType}*)p)->{tagField.Name}; }}");
                sb.AppendLine($"void {tagSet}(void* p, int64_t v) {{ (({structType}*)p)->{tagField.Name} = ({tagField.Type.Spelling})v; }}");
            }

            if (hostStruct.Fields.Any(f => string.Equals(f.Name, rule.PayloadField, StringComparison.Ordinal)))
            {
                var payloadPtr = RawBindingGenerator.StructFieldPtrShimName(rule.Struct!, rule.PayloadField!);
                sb.AppendLine($"void* {payloadPtr}(void* p) {{ return &(({structType}*)p)->{rule.PayloadField}; }}");
            }

            sb.AppendLine();
        }
    }

    /// <summary>
    /// union 成员视图访问器（M4a）：标量/指针成员值读写，聚合成员取地址。
    /// 入参为指向 union 的指针（void* + 内部转换到 union 类型）。
    /// </summary>
    private void GenerateUnionAccessors(StringBuilder sb, CBindingUnion union)
    {
        var unionType = _typedefs.ContainsKey(union.Name) ? union.Name : $"union {union.Name}";
        foreach (var field in union.Fields.OrderBy(static f => f.Name, StringComparer.Ordinal))
        {
            var mapping = _typeMapper.Map(field.Type);
            var isAggregate = mapping.Category is not (BindingTypeCategory.Direct or
                BindingTypeCategory.RawPtr or
                BindingTypeCategory.EnumAsInt);
            var shimGet = RawBindingGenerator.UnionShimName(union.Name, field.Name, "get");
            var shimSet = RawBindingGenerator.UnionShimName(union.Name, field.Name, "set");

            if (isAggregate)
            {
                sb.AppendLine($"void* {shimGet}(void* p) {{ return &(({unionType}*)p)->{field.Name}; }}");
                continue;
            }

            var memberSpelling = field.Type.Spelling;
            if (mapping.Category == BindingTypeCategory.EnumAsInt)
            {
                // enum 成员：Eidos 侧 Int（i64），shim 侧 int64_t 宽化 + 枚举窄化。
                sb.AppendLine($"int64_t {shimGet}(void* p) {{ return (int64_t)(({unionType}*)p)->{field.Name}; }}");
                sb.AppendLine($"void {shimSet}(void* p, int64_t v) {{ (({unionType}*)p)->{field.Name} = ({field.Type.Spelling})v; }}");
                continue;
            }

            sb.AppendLine($"{memberSpelling} {shimGet}(void* p) {{ return (({unionType}*)p)->{field.Name}; }}");
            sb.AppendLine($"void {shimSet}(void* p, {memberSpelling} v) {{ (({unionType}*)p)->{field.Name} = v; }}");
        }
    }

    private bool NeedsShim(CBindingFunction fn)
    {
        // 与 RawBindingGenerator.CanBindFunction 保持一致：任一 struct 参数不可拆分时
        // 整个函数不可绑定，也不生成 shim（否则会产出缺参数的坏 C 代码）。
        foreach (var parameter in fn.Parameters)
        {
            if (_typeMapper.Map(parameter.Type).Category == BindingTypeCategory.StructByValue &&
                !CanSplitStruct(parameter.Type))
            {
                return false;
            }
        }

        return fn.Parameters.Any(parameter => NeedsShim(parameter.Type)) ||
               NeedsShim(fn.ReturnType);
    }

    private bool NeedsShim(CBindingType type)
    {
        var mapping = _typeMapper.Map(type);
        return mapping.Category == BindingTypeCategory.StructByValue
            ? type.Kind == CBindingTypeKind.Struct || type.Kind == CBindingTypeKind.Typedef && CanSplitStruct(type)
            : type.Kind is CBindingTypeKind.Primitive or CBindingTypeKind.Enum && NeedsNarrowing(type);
    }

    /// <summary>
    /// 窄化 shim 只服务"仍映射为 64 位 Eidos 标量"的窄 C 尺寸：enum（EnumAsInt → Int）与
    /// 无布局事实的残留路径。char/short/int 与 float 已直接映射 Eidos 窄标量（E5337 收口），
    /// 以原生位宽过 FFI 边界，不再生成 shim。Size==0（简单模式）视为未知 → 不 shim。
    /// </summary>
    private bool NeedsNarrowing(CBindingType type) =>
        type.Size is not (0 or 8) &&
        !(type.Kind == CBindingTypeKind.Primitive && type.Name is "bool" or "_Bool") &&
        _typeMapper.Map(type).EidosType is "Int" or "Int64" or "Float";

    private bool CanSplitStruct(CBindingType type) =>
        TrySplitStruct(type, "p", 0, out _, out _);

    private void GenerateShim(StringBuilder sb, CBindingFunction fn)
    {
        if (_typeMapper.Map(fn.ReturnType).Category == BindingTypeCategory.StructByValue)
        {
            GenerateStaticSlotReturnShim(sb, fn);
            return;
        }

        GenerateScalarShim(sb, fn);
    }

    private void GenerateScalarShim(StringBuilder sb, CBindingFunction fn)
    {
        var shimName = $"eidos_shim_{fn.Name}";
        var returnNarrowing = IsNarrowing(fn.ReturnType);
        var shimReturnType = returnNarrowing ? WideScalarType(fn.ReturnType) : fn.ReturnType.Spelling;

        BuildParametersAndArguments(fn, out var parameters, out var arguments);

        sb.Append($"{shimReturnType} {shimName}(");
        sb.Append(string.Join(", ", parameters));
        sb.AppendLine(")");
        sb.AppendLine("{");
        if (returnNarrowing)
        {
            sb.Append($"    return ({WideScalarType(fn.ReturnType)}){fn.Name}(");
            sb.Append(string.Join(", ", arguments));
            sb.AppendLine(");");
        }
        else
        {
            if (shimReturnType != "void")
                sb.Append("    return ");
            else
                sb.Append("    ");
            sb.Append($"{fn.Name}(");
            sb.Append(string.Join(", ", arguments));
            sb.AppendLine(");");
        }

        sb.AppendLine("}");
    }

    /// <summary>
    /// struct 按值返回：静态槽 + 指针返回。Eidos 侧绑定 <c>-> RawPtr</c>，
    /// 调用方在下次调用前复制字段（单静态槽，不可重入）。
    /// </summary>
    private void GenerateStaticSlotReturnShim(StringBuilder sb, CBindingFunction fn)
    {
        var shimName = $"eidos_shim_{fn.Name}";
        var returnType = fn.ReturnType.Spelling;

        BuildParametersAndArguments(fn, out var parameters, out var arguments);

        sb.AppendLine($"// {fn.ReturnType.Name} returned by value through a single static slot;");
        sb.AppendLine($"// callers must copy the result before the next call to {shimName}.");
        sb.AppendLine($"static {returnType} {shimName}_result;");
        sb.Append($"{returnType}* {shimName}(");
        sb.Append(string.Join(", ", parameters));
        sb.AppendLine(")");
        sb.AppendLine("{");
        sb.Append($"    {shimName}_result = {fn.Name}(");
        sb.Append(string.Join(", ", arguments));
        sb.AppendLine(");");
        sb.AppendLine($"    return &{shimName}_result;");
        sb.AppendLine("}");
    }

    private void BuildParametersAndArguments(
        CBindingFunction fn,
        out List<string> parameters,
        out List<string> arguments)
    {
        parameters = [];
        arguments = [];
        foreach (var parameter in fn.Parameters)
        {
            if (_typeMapper.Map(parameter.Type).Category == BindingTypeCategory.StructByValue)
            {
                if (!TrySplitStruct(parameter.Type, parameter.Name, 0, out var fields, out var literal))
                    continue; // NeedsShim 已保证可拆分；不可拆分的函数由 RawBindingGenerator SKIP

                foreach (var field in fields)
                {
                    parameters.Add($"{field.ShimType} {field.ParamName}");
                }

                arguments.Add(literal);
            }
            else if (NeedsNarrowing(parameter.Type))
            {
                parameters.Add($"{WideScalarType(parameter.Type)} {parameter.Name}");
                arguments.Add($"({parameter.Type.Spelling}){parameter.Name}");
            }
            else
            {
                parameters.Add($"{parameter.Type.Spelling} {parameter.Name}");
                arguments.Add(parameter.Name);
            }
        }
    }

    /// <summary>
    /// struct 按值参数递归拆分：叶字段以原生位宽产出 shim 参数与 compound literal
    /// 成员表达式（enum 叶保持 int64_t 宽化 + cast，对齐 Eidos 侧 Int）；
    /// 嵌套 struct 递归组装。
    /// </summary>
    private bool TrySplitStruct(CBindingType type, string paramName, int depth, out List<SplitField> fields, out string literal)
    {
        fields = [];
        literal = "";
        if (depth > 16)
            return false;

        if (type.Kind == CBindingTypeKind.Struct)
        {
            if (!_structsByName.TryGetValue(type.Name, out var st) || st.Fields.Count == 0)
                return false;

            var members = new List<string>();
            foreach (var field in st.Fields)
            {
                var fieldParamName = $"{paramName}_{BindingTypeMapper.ToEidosFunctionName(field.Name)}";
                if (!TrySplitStruct(field.Type, fieldParamName, depth + 1, out var nestedFields, out var member))
                    return false;

                fields.AddRange(nestedFields);
                members.Add(member);
            }

            literal = $"({type.Spelling}){{ {string.Join(", ", members)} }}";
            return true;
        }

        if (type.Kind == CBindingTypeKind.Typedef && _typedefs.TryGetValue(type.Name, out var typedef))
        {
            var underlying = typedef.UnderlyingType ?? new CBindingType(typedef.UnderlyingKind, typedef.Underlying, typedef.Underlying);
            return TrySplitStruct(underlying, paramName, depth + 1, out fields, out literal);
        }

        if (type.Kind is CBindingTypeKind.Union or CBindingTypeKind.Array)
            return false;

        if (type.Kind == CBindingTypeKind.Pointer)
        {
            fields.Add(new SplitField(paramName, type.Spelling, paramName));
            literal = paramName;
            return true;
        }

        if (type.Kind == CBindingTypeKind.Primitive)
        {
            // 叶字段以原生位宽直连（与 Eidos 侧 Map 产出的窄标量签名一致）；
            // 仅 enum 叶（下方）保持 int64_t 宽化 + cast。
            fields.Add(new SplitField(paramName, type.Spelling, paramName));
            literal = paramName;
            return true;
        }

        if (type.Kind == CBindingTypeKind.Enum)
        {
            fields.Add(new SplitField(paramName, "int64_t", $"({type.Spelling}){paramName}"));
            literal = $"({type.Spelling}){paramName}";
            return true;
        }

        return false;
    }

    private bool IsNarrowing(CBindingType type) =>
        (type.Kind is CBindingTypeKind.Primitive or CBindingTypeKind.Enum) && NeedsNarrowing(type);

    /// <summary>
    /// 窄标量的 shim 侧宽类型：<c>float</c> → <c>double</c>；其余（整数/enum）→ <c>int64_t</c>。
    /// </summary>
    private static string WideScalarType(CBindingType type) =>
        type.Name == "float" ? "double" : "int64_t";

    private sealed record SplitField(string ParamName, string ShimType, string LiteralMember);
}

