using System.Text;

namespace Eidosc.Bindgen;

public sealed record RawBindingGenerationResult(string Source, IReadOnlyDictionary<string, string> RawFunctionNames);

public sealed class RawBindingGenerator
{
    private readonly BindingSpecDocument _spec;
    private readonly CHeaderIr _ir;
    private readonly BindingTypeMapper _typeMapper;

    public RawBindingGenerator(BindingSpecDocument spec, CHeaderIr ir)
    {
        _spec = spec;
        _ir = ir;
        _typeMapper = new BindingTypeMapper(ir);
    }

    public RawBindingGenerationResult Generate()
    {
        var rawFunctionNames = new Dictionary<string, string>(StringComparer.Ordinal);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by eidosc pkg bind. Do not edit this file directly.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("Raw :: module {");

        GenerateEnums(sb);
        GenerateStructs(sb);
        GenerateFunctions(sb, rawFunctionNames);

        sb.AppendLine("}");
        return new RawBindingGenerationResult(sb.ToString(), rawFunctionNames);
    }

    private void GenerateEnums(StringBuilder sb)
    {
        foreach (var en in _ir.Enums)
        {
            foreach (var value in en.Values)
            {
                sb.AppendLine($"    export {BindingTypeMapper.ToEidosFunctionName(value.Name)} :: Int = {value.Value};");
            }

            if (en.Values.Count > 0)
                sb.AppendLine();
        }
    }

    private void GenerateStructs(StringBuilder sb)
    {
        foreach (var st in _ir.Structs)
        {
            if (st.Fields.Count == 0)
                continue;

            sb.AppendLine($"    export {st.Name} :: type repr c {{");
            foreach (var field in st.Fields)
            {
                var mapping = _typeMapper.Map(field.Type);
                if (mapping.Category == BindingTypeCategory.Unsupported)
                    continue;

                sb.AppendLine($"        {BindingTypeMapper.ToEidosFunctionName(field.Name)} :: {mapping.EidosType},");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    private void GenerateFunctions(StringBuilder sb, Dictionary<string, string> rawFunctionNames)
    {
        foreach (var fn in _ir.Functions.OrderBy(static f => f.Name, StringComparer.Ordinal))
        {
            var eidosName = BindingTypeMapper.ToEidosFunctionName(fn.Name);
            rawFunctionNames[fn.Name] = eidosName;

            var (canBind, reason) = CanBindFunction(fn);
            if (!canBind)
            {
                sb.AppendLine($"    // SKIP {fn.Name}: {reason}");
                continue;
            }

            var needsShim = NeedsShim(fn);
            var ffiName = needsShim ? $"eidos_shim_{fn.Name}" : fn.Name;
            sb.AppendLine($"    export {eidosName} :: {FormatSignature(fn, needsShim)} need ffi extern(c, name: \"{ffiName}\");");
            sb.AppendLine();
        }
    }

    private (bool CanBind, string Reason) CanBindFunction(CBindingFunction fn)
    {
        if (fn.IsVariadic)
            return (false, "variadic functions require a fixed-signature C wrapper");

        var returnMapping = _typeMapper.Map(fn.ReturnType);
        if (returnMapping.Category == BindingTypeCategory.Unsupported)
            return (false, returnMapping.Note ?? $"unsupported return type {fn.ReturnType.Spelling}");
        if (returnMapping.Category == BindingTypeCategory.StructByValue)
            return (false, "struct-by-value returns require an explicit pointer-returning wrapper");

        foreach (var parameter in fn.Parameters)
        {
            var mapping = _typeMapper.Map(parameter.Type);
            if (mapping.Category == BindingTypeCategory.Unsupported)
                return (false, mapping.Note ?? $"unsupported parameter type {parameter.Type.Spelling}");
        }

        return (true, "");
    }

    private bool NeedsShim(CBindingFunction fn) =>
        fn.Parameters.Any(parameter => _typeMapper.Map(parameter.Type).Category == BindingTypeCategory.StructByValue);

    private string FormatSignature(CBindingFunction fn, bool useShimTypes)
    {
        var returnType = _typeMapper.Map(fn.ReturnType).EidosType;
        if (fn.Parameters.Count == 0)
            return $"Unit -> {returnType}";

        var parameterTypes = fn.Parameters
            .Select(parameter =>
            {
                var mapping = _typeMapper.Map(parameter.Type);
                return useShimTypes && mapping.Category == BindingTypeCategory.StructByValue
                    ? "RawPtr"
                    : mapping.EidosType;
            });
        return $"{string.Join(" -> ", parameterTypes)} -> {returnType}";
    }
}
