using System.Text;
using System.Text.Json;

namespace Eidosc.Bindgen;

public sealed record RawBindingGenerationResult(string Source, IReadOnlyDictionary<string, string> RawFunctionNames);

public sealed class RawBindingGenerator
{
    private readonly BindingSpecDocument _spec;
    private readonly CHeaderIr _ir;
    private readonly BindingTypeMapper _typeMapper;

    public RawBindingGenerator(BindingSpecDocument spec, CHeaderIr ir)
    {
        _spec = spec;
        _ir = ir;
        _typeMapper = new BindingTypeMapper(ir);
    }

    public RawBindingGenerationResult Generate()
    {
        var rawFunctionNames = new Dictionary<string, string>(StringComparer.Ordinal);
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by eidosc pkg bind. Do not edit this file directly.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("Raw :: module {");

        GenerateEnums(sb, usedNames);
        GenerateStructs(sb, usedNames);
        GenerateConstants(sb, usedNames);
        GenerateSkippedDeclarations(sb);
        GenerateFunctions(sb, rawFunctionNames, usedNames);

        sb.AppendLine("}");
        return new RawBindingGenerationResult(sb.ToString(), rawFunctionNames);
    }

    private void GenerateEnums(StringBuilder sb, HashSet<string> usedNames)
    {
        foreach (var en in _ir.Enums)
        {
            foreach (var value in en.Values)
            {
                var eidosName = BindingTypeMapper.ToEidosFunctionName(value.Name);
                usedNames.Add(eidosName);
                sb.AppendLine($"    export {eidosName} :: Int = {value.Value};");
            }

            if (en.Values.Count > 0)
                sb.AppendLine();
        }
    }

    private void GenerateStructs(StringBuilder sb, HashSet<string> usedNames)
    {
        foreach (var st in _ir.Structs)
        {
            if (st.Fields.Count == 0)
            {
                sb.AppendLine($"    // SKIP struct {st.Name}: no fields (incomplete or forward declaration)");
                continue;
            }

            if (BindingTypeMapper.IsEidosKeyword(st.Name))
            {
                sb.AppendLine($"    // SKIP struct {st.Name}: name collides with an Eidos keyword");
                continue;
            }

            var fieldNames = new HashSet<string>(StringComparer.Ordinal);
            var emittedFields = new List<string>();
            foreach (var field in st.Fields)
            {
                var mapping = _typeMapper.Map(field.Type);
                if (mapping.Category == BindingTypeCategory.Unsupported)
                    continue;

                var fieldName = BindingTypeMapper.ToEidosFunctionName(field.Name);
                if (!fieldNames.Add(fieldName))
                    continue;

                emittedFields.Add($"        {fieldName} :: {mapping.EidosType},");
            }

            if (emittedFields.Count == 0)
            {
                sb.AppendLine($"    // SKIP struct {st.Name}: no FFI-safe fields; use pointer-based shims");
                continue;
            }

            usedNames.Add(st.Name);
            sb.AppendLine("    @[repr(c)]");
            sb.AppendLine($"    export {st.Name} :: type {{");
            foreach (var field in emittedFields)
                sb.AppendLine(field);

            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// 对象式宏常量 → Eidos 常量。数值宏映射为 <c>Int</c>，字符串宏映射为 <c>String</c>
    /// （不跨 FFI，仅作模块内常量）。名称冲突时跳过并注释，不产出重复 export。
    /// </summary>
    private void GenerateConstants(StringBuilder sb, HashSet<string> usedNames)
    {
        foreach (var constant in _ir.ConstantsSafe)
        {
            var eidosName = BindingTypeMapper.ToEidosFunctionName(constant.Name);
            if (!usedNames.Add(eidosName))
            {
                sb.AppendLine($"    // SKIP constant {constant.Name}: name collides with another generated declaration");
                continue;
            }

            if (constant.IsString)
                sb.AppendLine($"    export {eidosName} :: String = {JsonSerializer.Serialize(constant.Value)};");
            else
                sb.AppendLine($"    export {eidosName} :: Int = {constant.Value};");
        }

        if (_ir.ConstantsSafe.Count > 0)
            sb.AppendLine();
    }

    /// <summary>
    /// 无法在 Eidos 中表达或需要 shim 的声明：union、全局变量、typedef 链。
    /// P0 只收编为注释（语义事实保留在生成文件里），shim 收编在 M4。
    /// </summary>
    private void GenerateSkippedDeclarations(StringBuilder sb)
    {
        var emitted = false;
        foreach (var u in _ir.UnionsSafe)
        {
            sb.AppendLine($"    // SKIP union {u.Name}: unions are not representable in Eidos; use pointer-based shims");
            emitted = true;
        }

        foreach (var g in _ir.GlobalsSafe)
        {
            sb.AppendLine($"    // SKIP global {g.Name}: Eidos has no module-level mutable state; expose via shims");
            emitted = true;
        }

        foreach (var t in _ir.TypedefsSafe)
        {
            sb.AppendLine($"    // typedef {t.Name} -> {t.Underlying}");
            emitted = true;
        }

        if (emitted)
            sb.AppendLine();
    }

    private void GenerateFunctions(StringBuilder sb, Dictionary<string, string> rawFunctionNames, HashSet<string> usedNames)
    {
        foreach (var fn in _ir.Functions.OrderBy(static f => f.Name, StringComparer.Ordinal))
        {
            var eidosName = BindingTypeMapper.ToEidosFunctionName(fn.Name);
            rawFunctionNames[fn.Name] = eidosName;

            var (canBind, reason) = CanBindFunction(fn);
            if (!canBind)
            {
                sb.AppendLine($"    // SKIP {fn.Name}: {reason}");
                continue;
            }

            if (!usedNames.Add(eidosName))
            {
                sb.AppendLine($"    // SKIP {fn.Name}: generated name '{eidosName}' collides with another declaration");
                continue;
            }

            var needsShim = NeedsShim(fn);
            var ffiName = needsShim ? $"eidos_shim_{fn.Name}" : fn.Name;
            sb.AppendLine($"    @[extern(c, name: \"{ffiName}\")]");
            sb.AppendLine($"    export {eidosName} :: {FormatSignature(fn, needsShim)} need ffi;");
            sb.AppendLine();
        }
    }

    private (bool CanBind, string Reason) CanBindFunction(CBindingFunction fn)
    {
        if (fn.IsVariadic)
            return (false, "variadic functions require a fixed-signature C wrapper");

        var returnMapping = _typeMapper.Map(fn.ReturnType);
        if (returnMapping.Category == BindingTypeCategory.Unsupported)
            return (false, returnMapping.Note ?? $"unsupported return type {fn.ReturnType.Spelling}");
        // struct 按值返回经静态槽 shim 绑定为 RawPtr（BindingCShimGenerator）。

        foreach (var parameter in fn.Parameters)
        {
            var mapping = _typeMapper.Map(parameter.Type);
            if (mapping.Category == BindingTypeCategory.Unsupported)
                return (false, mapping.Note ?? $"unsupported parameter type {parameter.Type.Spelling}");
        }

        return (true, "");
    }

    private bool NeedsShim(CBindingFunction fn) =>
        fn.Parameters.Any(parameter => _typeMapper.Map(parameter.Type).Category == BindingTypeCategory.StructByValue) ||
        _typeMapper.Map(fn.ReturnType).Category == BindingTypeCategory.StructByValue;

    private string FormatSignature(CBindingFunction fn, bool useShimTypes)
    {
        var returnType = _typeMapper.Map(fn.ReturnType).EidosType;
        if (fn.Parameters.Count == 0)
            return $"Unit -> {returnType}";

        var parameterTypes = fn.Parameters
            .Select(parameter =>
            {
                var mapping = _typeMapper.Map(parameter.Type);
                return useShimTypes && mapping.Category == BindingTypeCategory.StructByValue
                    ? "RawPtr"
                    : mapping.EidosType;
            });
        return $"{string.Join(" -> ", parameterTypes)} -> {returnType}";
    }
}
