using System.Text;

namespace Eidosc.Bindgen;

public sealed record WrapperFile(string ModulePath, string Source);

public sealed class WrapperBindingGenerator
{
    private readonly BindingSpecDocument _spec;
    private readonly CHeaderIr _ir;
    private readonly IReadOnlyDictionary<string, string> _rawFunctionNames;
    private readonly BindingTypeMapper _typeMapper;

    public WrapperBindingGenerator(
        BindingSpecDocument spec,
        CHeaderIr ir,
        IReadOnlyDictionary<string, string> rawFunctionNames)
    {
        _spec = spec;
        _ir = ir;
        _rawFunctionNames = rawFunctionNames;
        _typeMapper = new BindingTypeMapper(ir);
    }

    public IReadOnlyList<WrapperFile> Generate()
    {
        var wrappers = _spec.Wrappers ?? [];
        if (wrappers.Length == 0)
            return [];

        var functions = _ir.Functions.ToDictionary(static f => f.Name, StringComparer.Ordinal);
        var byModule = wrappers.GroupBy(static w => w.Module!, StringComparer.Ordinal);
        var files = new List<WrapperFile>();
        foreach (var moduleGroup in byModule)
        {
            var modulePath = moduleGroup.Key.Replace('\\', '.').Replace('/', '.');
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by eidosc pkg bind. Do not edit this file directly.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine($"{modulePath} :: module {{");
            sb.AppendLine("    import Raw");
            sb.AppendLine();
            GenerateAbilities(sb, moduleGroup);

            foreach (var wrapper in moduleGroup)
            {
                if (!functions.TryGetValue(wrapper.Raw!, out var fn))
                    throw new InvalidOperationException($"Wrapper '{wrapper.Name}' references unknown raw symbol '{wrapper.Raw}'.");
                if (!_rawFunctionNames.TryGetValue(fn.Name, out var rawName))
                    throw new InvalidOperationException($"Wrapper '{wrapper.Name}' references ungenerated raw symbol '{wrapper.Raw}'.");

                var signature = string.IsNullOrWhiteSpace(wrapper.Signature)
                    ? FormatSignature(fn)
                    : wrapper.Signature!;
                var abilitySuffix = wrapper.Effects is { Length: > 0 }
                    ? $" need {string.Join(", ", wrapper.Effects)}"
                    : "";

                sb.AppendLine($"    export {wrapper.Name} :: {signature}{abilitySuffix}");
                sb.AppendLine("    {");
                sb.AppendLine($"        {FormatBranch(fn, rawName)}");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            files.Add(new WrapperFile(modulePath, sb.ToString()));
        }

        return files;
    }

    private void GenerateAbilities(StringBuilder sb, IEnumerable<BindingWrapperRule> wrappers)
    {
        var abilityNames = wrappers
            .SelectMany(static wrapper => wrapper.Effects ?? [])
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        if (abilityNames.Length == 0)
            return;

        var abilityRules = (_spec.Effects ?? [])
            .ToDictionary(static ability => ability.Name!, StringComparer.Ordinal);
        foreach (var abilityName in abilityNames)
        {
            sb.AppendLine($"    export {abilityName} :: ability {{");
            if (abilityRules.TryGetValue(abilityName, out var rule))
            {
                foreach (var operation in rule.Operations ?? [])
                    sb.AppendLine($"        {operation}");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    private string FormatSignature(CBindingFunction fn)
    {
        var returnType = _typeMapper.Map(fn.ReturnType).EidosType;
        if (fn.Parameters.Count == 0)
            return $"Unit -> {returnType}";

        var parameterTypes = fn.Parameters.Select(parameter => _typeMapper.Map(parameter.Type).EidosType);
        return $"{string.Join(" -> ", parameterTypes)} -> {returnType}";
    }

    private static string FormatBranch(CBindingFunction fn, string rawName)
    {
        if (fn.Parameters.Count == 0)
            return $"_ => Raw.{rawName}()";

        var args = Enumerable.Range(0, fn.Parameters.Count)
            .Select(i => $"arg{i}")
            .ToArray();
        return $"({string.Join(", ", args)}) => Raw.{rawName}({string.Join(", ", args)})";
    }
}
