<Project>
  <Import Project="$(MSBuildThisFileDirectory)Eidos.Version.props" />
  <PropertyGroup>
    <EidosupVersion>$(EidosVersion)</EidosupVersion>
    <Version>$(EidosVersion)</Version>
    <AssemblyVersion>$(EidosAssemblyVersion)</AssemblyVersion>
    <FileVersion>$(EidosAssemblyVersion)</FileVersion>
    <InformationalVersion>$(EidosVersion)</InformationalVersion>
  </PropertyGroup>
</Project>
