using System.Text;

namespace Eidosc.Bindgen.Clang;

/// <summary>
/// C2E 垂直切片（M7）：把 C 函数体源到源翻译为 Eidos 函数。
/// 支持子集：int/float 标量算术与比较、局部变量（声明/赋值）、if/else、
/// while/for（经 loop+break 去糖）、return、对同文件已翻译函数的调用、
/// 整数字面量。C 定宽整数溢出不建模（统一提升为 Eidos Int/Float，值域内语义一致）；
/// 其余构造（指针、数组、字符串、switch/goto/三目、复合赋值、自增自减、
/// 跨类型混合算术）不支持——所在函数跳过并注释。
/// </summary>
internal sealed class CBodyTranslator
{
    private readonly ClangApi _api;

    public CBodyTranslator(ClangApi api)
    {
        _api = api;
    }

    internal sealed record C2EResult(string Source, IReadOnlyList<string> SkippedFunctions)
    {
        public bool IsEmpty => Source.Length == 0;
    }

    public C2EResult Translate(string cSourcePath)
    {
        using var session = new ClangSession(_api);
        session.Parse(cSourcePath, skipFunctionBodies: false);
        var functions = new List<ClangCursor>();
        session.VisitChildren(session.RootCursor, (cursor, _, _) =>
        {
            if ((ClangCursorKind)cursor.Kind == ClangCursorKind.FunctionDecl)
            {
                functions.Add(cursor);
            }

            return ClangChildVisitResult.Continue;
        }, IntPtr.Zero);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Translated from C by the Eidos C2E vertical slice. Do not edit.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        var skipped = new List<string>();
        var translatedNames = new HashSet<string>(StringComparer.Ordinal);
        var defined = functions
            .Where(HasBody)
            .Select(f => _api.GetString(_api.GetCursorSpelling(f)))
            .ToHashSet(StringComparer.Ordinal);
        foreach (var function in functions)
        {
            var name = _api.GetString(_api.GetCursorSpelling(function));
            if (!HasBody(function) || name == "main")
            {
                continue;
            }

            var translated = TryTranslateFunction(function, defined);
            if (translated == null)
            {
                skipped.Add(name);
                sb.AppendLine($"// SKIP {name}: {SkipReason}");
                sb.AppendLine();
                continue;
            }

            translatedNames.Add(name);
            sb.AppendLine(translated);
        }

        return new C2EResult(sb.ToString(), skipped);
    }

    private string? SkipReason { get; set; }

    private bool HasBody(ClangCursor function) =>
        Children(function).Any(static child => child.Kind == ClangCursorKind2.CompoundStmt);

    private string? TryTranslateFunction(ClangCursor function, HashSet<string> definedNames)
    {
        SkipReason = null;
        var name = _api.GetString(_api.GetCursorSpelling(function));
        var children = Children(function);
        var body = children.FirstOrDefault(static c => c.Kind == ClangCursorKind2.CompoundStmt);

        // 参数类型：全部映射 Int/Float，其余不支持。
        var paramTypes = new List<string>();
        var paramNames = new List<string>();
        foreach (var child in children)
        {
            if ((ClangCursorKind)child.Kind != ClangCursorKind.ParmDecl)
            {
                continue;
            }

            var eidosType = MapScalarType(_api.GetCursorType(child));
            if (eidosType == null)
            {
                SkipReason = $"parameter '{_api.GetString(_api.GetCursorSpelling(child))}' has unsupported type";
                return null;
            }

            paramTypes.Add(eidosType);
            paramNames.Add(_api.GetString(_api.GetCursorSpelling(child)));
        }

        var returnType = MapScalarType(_api.GetCursorResultType(function));
        if (returnType == null)
        {
            SkipReason = "return type is not a supported scalar";
            return null;
        }

        var context = new FunctionContext(definedNames);
        var bodyText = TranslateStatements(Children(body), context, isTopLevel: true);
        if (bodyText == null)
        {
            return null;
        }

        var signature = paramTypes.Count == 0
            ? $"Unit -> {returnType}"
            : $"{string.Join(" -> ", paramTypes)} -> {returnType}";
        var binders = paramNames.Count == 0
            ? "_ =>"
            : string.Join(" => ", paramNames) + " =>";
        var tail = returnType == "Unit" ? "()" : "0";

        var sb = new StringBuilder();
        sb.AppendLine($"{name} :: {signature}");
        sb.AppendLine("{");
        sb.AppendLine($"    {binders} {{");
        sb.AppendLine(Indent(bodyText, 8));
        sb.AppendLine($"        {tail}");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private string? TranslateStatements(List<ClangCursor> statements, FunctionContext context, bool isTopLevel)
    {
        var lines = new List<string>();
        foreach (var statement in statements)
        {
            var line = TranslateStatement(statement, context);
            if (line == null)
            {
                return null;
            }

            lines.Add(line);
        }

        return string.Join(Environment.NewLine, lines);
    }

    private string? TranslateStatement(ClangCursor statement, FunctionContext context)
    {
        switch (statement.Kind)
        {
            case ClangCursorKind2.DeclStmt:
            {
                var lines = new List<string>();
                foreach (var varDecl in Children(statement))
                {
                    if ((ClangCursorKind)varDecl.Kind != ClangCursorKind.VarDecl)
                    {
                        SkipReason = "unsupported declaration in statement";
                        return null;
                    }

                    var varName = _api.GetString(_api.GetCursorSpelling(varDecl));
                    var varType = MapScalarType(_api.GetCursorType(varDecl));
                    if (varType == null)
                    {
                        SkipReason = $"local '{varName}' has unsupported type";
                        return null;
                    }

                    var initChildren = Children(varDecl);
                    var init = initChildren.Count > 0 ? TranslateExpression(initChildren[0], context) : "0";
                    if (init == null)
                    {
                        return null;
                    }

                    context.Locals.Add(varName);
                    context.Types[varName] = varType;
                    lines.Add($"mut {varName} := {init};");
                }

                return string.Join(Environment.NewLine, lines);
            }

            case ClangCursorKind2.CompoundStmt:
            {
                var inner = TranslateStatements(Children(statement), context, isTopLevel: false);
                return inner == null ? null : inner;
            }

            case ClangCursorKind2.ReturnStmt:
            {
                var valueChildren = Children(statement);
                if (valueChildren.Count == 0)
                {
                    return string.Empty;
                }

                var value = TranslateExpression(valueChildren[0], context);
                return value == null ? null : $"return {value};";
            }

            case ClangCursorKind2.IfStmt:
            {
                var parts = Children(statement);
                if (parts.Count is < 2 or > 3)
                {
                    SkipReason = "unsupported if form";
                    return null;
                }

                var condition = TranslateExpression(parts[0], context);
                if (condition == null)
                {
                    return null;
                }

                var thenBody = TranslateStatements(Children(parts[1]), context, isTopLevel: false);
                if (thenBody == null)
                {
                    return null;
                }

                string Brace(string inner) =>
                    $"{{{Environment.NewLine}{Indent(inner, 8)}{Environment.NewLine}    (){Environment.NewLine}}}";

                if (parts.Count == 3)
                {
                    var elseBody = parts[2].Kind == ClangCursorKind2.IfStmt
                        ? TranslateStatement(parts[2], context)
                        : TranslateStatements(Children(parts[2]), context, isTopLevel: false);
                    if (elseBody == null)
                    {
                        return null;
                    }

                    return $"if {condition} then{Brace(thenBody)} else{Brace(elseBody)};";
                }

                return $"if {condition} then{Brace(thenBody)} else {{ () }};";
            }

            case ClangCursorKind2.WhileStmt:
            {
                var parts = Children(statement);
                if (parts.Count != 2)
                {
                    SkipReason = "unsupported while form";
                    return null;
                }

                var condition = TranslateExpression(parts[0], context);
                if (condition == null)
                {
                    return null;
                }

                var body = TranslateStatements(Children(parts[1]), context, isTopLevel: false);
                if (body == null)
                {
                    return null;
                }

                return $"loop {{{Environment.NewLine}    if !({condition}) then break;{Environment.NewLine}{Indent(body, 4)}{Environment.NewLine}}};";
            }

            case ClangCursorKind2.ForStmt:
            {
                // init / cond / inc / body 去糖为声明 + loop。
                var parts = Children(statement);
                if (parts.Count != 4)
                {
                    SkipReason = "unsupported for form";
                    return null;
                }

                var init = TranslateStatement(parts[0], context);
                if (init == null || string.IsNullOrEmpty(init))
                {
                    SkipReason = "unsupported for-init";
                    return null;
                }

                var condition = TranslateExpression(parts[1], context);
                if (condition == null)
                {
                    return null;
                }

                var increment = TranslateExpression(parts[2], context, asStatement: true);
                if (increment == null)
                {
                    return null;
                }

                var body = TranslateStatements(Children(parts[3]), context, isTopLevel: false);
                if (body == null)
                {
                    return null;
                }

                var forSb = new StringBuilder();
                forSb.AppendLine(init);
                forSb.AppendLine("loop {");
                forSb.AppendLine($"    if !({condition}) then break;");
                forSb.AppendLine(Indent(body, 8));
                forSb.AppendLine($"    {increment};");
                forSb.AppendLine("    ()");
                forSb.AppendLine("}");
                return forSb.ToString();
            }

            default:
            {
                // 裸表达式语句（赋值/调用）。
                if (statement.Kind == ClangCursorKind2.BinaryOperator)
                {
                    return TranslateExpression(statement, context, asStatement: true) is { } expr
                        ? $"{expr};"
                        : null;
                }

                SkipReason = $"unsupported statement kind {statement.Kind}";
                return null;
            }
        }
    }

    private string? TranslateExpression(ClangCursor expression, FunctionContext context, bool asStatement = false)
    {
        switch (expression.Kind)
        {
            case ClangCursorKind2.UnexposedExpr:
            {
                var inner = Children(expression);
                return inner.Count == 1 ? TranslateExpression(inner[0], context, asStatement) : null;
            }

            case ClangCursorKind2.DeclRefExpr:
                return _api.GetString(_api.GetCursorSpelling(expression));

            case ClangCursorKind2.IntegerLiteral:
                return EvaluateLiteral(expression, integer: true);

            case ClangCursorKind2.FloatingLiteral:
                return EvaluateLiteral(expression, integer: false);

            case ClangCursorKind2.BinaryOperator:
            {
                var op = _api.GetString(_api.GetCursorSpelling(expression));
                var operands = Children(expression);
                if (operands.Count != 2)
                {
                    SkipReason = $"unsupported operand count for '{op}'";
                    return null;
                }

                if (op == "=")
                {
                    if (asStatement)
                    {
                        var target = TranslateExpression(operands[0], context);
                        var value = TranslateExpression(operands[1], context);
                        return target == null || value == null ? null : $"{target} := {value}";
                    }

                    SkipReason = "assignment used in expression context";
                    return null;
                }

                var left = TranslateExpression(operands[0], context);
                var right = TranslateExpression(operands[1], context);
                if (left == null || right == null)
                {
                    return null;
                }

                return op switch
                {
                    "+" or "-" or "*" or "/" or "%" or "<" or "<=" or ">" or ">=" or "==" or "!=" => $"{left} {op} {right}",
                    _ when op == "&&" => $"{left} && {right}",
                    _ when op == "||" => $"{left} || {right}",
                    _ => Skip(op),
                };

                string? Skip(string unsupported)
                {
                    SkipReason = $"unsupported operator '{unsupported}'";
                    return null;
                }
            }

            case ClangCursorKind2.CallExpr:
            {
                var operands = Children(expression);
                if (operands.Count == 0)
                {
                    SkipReason = "unsupported call form";
                    return null;
                }

                var callee = _api.GetString(_api.GetCursorSpelling(operands[0]));
                if (!context.DefinedNames.Contains(callee))
                {
                    SkipReason = $"call to untranslated function '{callee}'";
                    return null;
                }

                var arguments = new List<string>();
                foreach (var argument in operands.Skip(1))
                {
                    var translated = TranslateExpression(argument, context);
                    if (translated == null)
                    {
                        return null;
                    }

                    arguments.Add(translated);
                }

                return $"{callee}({string.Join(", ", arguments)})";
            }

            default:
                SkipReason = $"unsupported expression kind {expression.Kind}";
                return null;
        }
    }

    private string? EvaluateLiteral(ClangCursor literal, bool integer)
    {
        var result = _api.CursorEvaluate(literal);
        if (result == IntPtr.Zero)
        {
            SkipReason = "literal evaluation failed";
            return null;
        }

        try
        {
            var kind = _api.EvalResultGetKind(result);
            if (integer)
            {
                return _api.EvalResultGetAsLongLong(result).ToString();
            }

            // 浮点字面量：EvalResult 文本形式即十进制字面量。
            var text = _api.EvalResultGetAsStr(result);
            var ptr = text == IntPtr.Zero ? string.Empty : System.Runtime.InteropServices.Marshal.PtrToStringUTF8(text) ?? string.Empty;
            return string.IsNullOrWhiteSpace(text == IntPtr.Zero ? string.Empty : ptr) ? null : NormalizeFloat(ptr);
        }
        finally
        {
            _api.EvalResultDispose(result);
        }
    }

    private static string NormalizeFloat(string text)
    {
        if (text.Contains('e') || text.Contains('E') || text.Contains('.'))
        {
            return text;
        }

        return text + ".0";
    }

    private string? MapScalarType(ClangType type)
    {
        var canonical = _api.GetCanonicalType(type);
        return (ClangTypeKind)canonical.Kind switch
        {
            ClangTypeKind.Void => "Unit",
            ClangTypeKind.Int or ClangTypeKind.Long or ClangTypeKind.LongLong or
                ClangTypeKind.Short or ClangTypeKind.CharS or ClangTypeKind.SChar or
                ClangTypeKind.UInt or ClangTypeKind.ULong or ClangTypeKind.ULongLong or
                ClangTypeKind.UShort or ClangTypeKind.UChar or ClangTypeKind.CharU or
                ClangTypeKind.Bool or ClangTypeKind.Enum => "Int",
            ClangTypeKind.Float or ClangTypeKind.Double => "Float",
            _ => null
        };
    }

    private List<ClangCursor> Children(ClangCursor cursor)
    {
        var children = new List<ClangCursor>();
        _api.VisitChildren(cursor, (child, _, _) =>
        {
            children.Add(child);
            return ClangChildVisitResult.Continue;
        }, IntPtr.Zero);
        return children;
    }

    private static string Indent(string text, int width)
    {
        var pad = new string(' ', width);
        return string.Join(Environment.NewLine, text
            .Split(["\r\n", "\n"], StringSplitOptions.None)
            .Select(line => line.Length == 0 ? line : pad + line));
    }

    private sealed class FunctionContext(IReadOnlySet<string> definedNames)
    {
        public IReadOnlySet<string> DefinedNames { get; } = definedNames;
        public HashSet<string> Locals { get; } = new(StringComparer.Ordinal);
        public Dictionary<string, string> Types { get; } = new(StringComparer.Ordinal);
        public bool NeedsTailValue { get; set; } = true;
    }
}

/// <summary>
/// 语句/表达式 cursor kind（clang 22 实测值，与声明段枚举分离维护）。
/// </summary>
internal static class ClangCursorKind2
{
    internal const int UnexposedExpr = 100;
    internal const int DeclRefExpr = 101;
    internal const int IntegerLiteral = 106;
    internal const int FloatingLiteral = 107;
    internal const int BinaryOperator = 114;
    internal const int UnaryOperator = 115;
    internal const int CompoundStmt = 202;
    internal const int IfStmt = 205;
    internal const int WhileStmt = 207;
    internal const int ForStmt = 209;
    internal const int ReturnStmt = 214;
    internal const int DeclStmt = 231;
    internal const int CallExpr = 103;
}
