using System.Text;

namespace Eidosc.Bindgen.Clang;

/// <summary>
/// C2E 源到源翻译（M7 切片 + 特性矩阵扩展）：把 C 函数体翻译为 Eidos 函数。
/// 支持子集：int/float 标量算术与比较、一元 -/!/解引用、局部变量（声明/赋值）、
/// if/else、while/for（经 loop+break 去糖）、return、同文件已翻译函数的调用、
/// 指针（T* 映射 RawPtr：经 std.Ffi 的 load/store/pointer_eq/null_pointer）、
/// union/struct 指针的成员访问（经自动生成的 c2e_* C shim 与 extern(c) 声明）、
/// 对外部 C 函数的调用（自动生成 extern(c) 声明，C 侧由调用方链接）。
/// C 定宽整数溢出不建模（统一提升为 Eidos Int/Float，值域内语义一致）；
/// 其余构造（取地址 &、指针算术/下标、switch/goto/三目、复合赋值、自增自减、
/// 跨类型混合算术、按值传递的聚合）不支持——所在函数跳过并注释。
/// </summary>
internal sealed class CBodyTranslator
{
    private readonly ClangApi _api;
    private ClangSession? _session;

    public CBodyTranslator(ClangApi api)
    {
        _api = api;
    }

    internal sealed record C2EResult(
        string Source,
        string NativeShimSource,
        IReadOnlyList<string> SkippedFunctions)
    {
        public bool IsEmpty => Source.Length == 0;
    }

    /// <summary>被翻译函数引用的 union/struct 成员访问（生成 accessor shim 与 extern 声明）。</summary>
    private sealed record RecordMemberAccess(string RecordSpelling, string RecordName, string Member, string MemberCType, string MemberEidosType);

    /// <summary>被翻译函数调用的外部 C 函数。</summary>
    private sealed record PendingExtern(string CName, string EidosName, IReadOnlyList<string> ParameterTypes, string ReturnType);

    public C2EResult Translate(string cSourcePath)
    {
        using var session = new ClangSession(_api);
        _session = session;
        try
        {
            session.Parse(cSourcePath, skipFunctionBodies: false);
            var functions = new List<ClangCursor>();
            session.VisitChildren(session.RootCursor, (cursor, _, _) =>
            {
                if ((ClangCursorKind)cursor.Kind == ClangCursorKind.FunctionDecl)
                {
                    functions.Add(cursor);
                }

                return ClangChildVisitResult.Continue;
            }, IntPtr.Zero);

            var skipped = TranslateFunctions(functions, cSourcePath, out var source, out var shimSource);
            return new C2EResult(source, shimSource, skipped);
        }
        finally
        {
            _session = null;
        }
    }

    private List<string> TranslateFunctions(
        List<ClangCursor> functions,
        string cSourcePath,
        out string source,
        out string shimSource)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Translated from C by the Eidos C2E translator. Do not edit.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        var skipped = new List<string>();
        var declaredByName = new Dictionary<string, ClangCursor>(StringComparer.Ordinal);
        var defined = new HashSet<string>(StringComparer.Ordinal);
        foreach (var function in functions)
        {
            var name = _api.GetString(_api.GetCursorSpelling(function));
            declaredByName[name] = function;
            if (HasBody(function))
            {
                defined.Add(name);
            }
        }

        var state = new TranslationState(defined, declaredByName);
        foreach (var function in functions)
        {
            var name = _api.GetString(_api.GetCursorSpelling(function));
            if (!HasBody(function) || name == "main")
            {
                continue;
            }

            var parameterMappings = new List<CTypeMapping>();
            foreach (var child in Children(function))
            {
                if ((ClangCursorKind)child.Kind == ClangCursorKind.ParmDecl)
                {
                    parameterMappings.Add(MapType(_api.GetCursorType(child)) ?? UnsupportedMapping);
                }
            }

            state.FunctionParameters[name] = parameterMappings;
        }

        var bodies = new List<string>();
        foreach (var function in functions)
        {
            var name = _api.GetString(_api.GetCursorSpelling(function));
            if (!HasBody(function) || name == "main")
            {
                continue;
            }

            var translated = TryTranslateFunction(function, state);
            if (translated == null)
            {
                skipped.Add(name);
                bodies.Add($"// SKIP {name}: {SkipReason}");
                bodies.Add(string.Empty);
                continue;
            }

            bodies.Add(translated);
        }

        foreach (var externDeclaration in state.PendingExterns.Values)
        {
            sb.AppendLine($"@[extern(c, name: \"{externDeclaration.CName}\")]");
            var signature = externDeclaration.ParameterTypes.Count == 0
                ? $"Unit -> {externDeclaration.ReturnType}"
                : $"{string.Join(" -> ", externDeclaration.ParameterTypes)} -> {externDeclaration.ReturnType}";
            sb.AppendLine($"{externDeclaration.EidosName} :: {signature} need ffi;");
            sb.AppendLine();
        }

        foreach (var access in state.RecordMembers.Values)
        {
            var prefix = $"c2e_{access.RecordName}_{access.Member}";
            sb.AppendLine($"@[extern(c, name: \"{prefix}_get\")]");
            sb.AppendLine($"{prefix}_get :: RawPtr -> {access.MemberEidosType} need ffi;");
            sb.AppendLine($"@[extern(c, name: \"{prefix}_set\")]");
            sb.AppendLine($"{prefix}_set :: RawPtr -> {access.MemberEidosType} -> Unit need ffi;");
            sb.AppendLine();
        }

        if (state.NeedsFfiImport)
        {
            sb.AppendLine("import std.Ffi");
            sb.AppendLine();
        }

        foreach (var body in bodies)
        {
            sb.AppendLine(body);
        }

        source = sb.ToString();
        shimSource = BuildRecordMemberShimSource(cSourcePath, state.RecordMembers.Values);
        return skipped;
    }

    private string BuildRecordMemberShimSource(string cSourcePath, IEnumerable<RecordMemberAccess> accesses)
    {
        var list = accesses.ToList();
        if (list.Count == 0)
        {
            return string.Empty;
        }

        var shim = new StringBuilder();
        shim.AppendLine("// <auto-generated>");
        shim.AppendLine("// Accessor shims for union/struct member access emitted by the Eidos C2E translator.");
        shim.AppendLine("// </auto-generated>");
        shim.AppendLine($"#include \"{cSourcePath.Replace('\\', '/')}\"");
        shim.AppendLine();
        foreach (var access in list)
        {
            var prefix = $"c2e_{access.RecordName}_{access.Member}";
            shim.AppendLine($"static {access.MemberCType} {prefix}_get(void* __p) {{ return (({access.RecordSpelling}*)__p)->{access.Member}; }}");
            shim.AppendLine($"static void {prefix}_set(void* __p, {access.MemberCType} __v) {{ (({access.RecordSpelling}*)__p)->{access.Member} = __v; }}");
        }

        return shim.ToString();
    }

    private string? SkipReason { get; set; }

    private bool HasBody(ClangCursor function) =>
        Children(function).Any(static child => child.Kind == ClangCursorKind2.CompoundStmt);

    private string? TryTranslateFunction(ClangCursor function, TranslationState state)
    {
        SkipReason = null;
        var children = Children(function);
        var body = children.FirstOrDefault(static c => c.Kind == ClangCursorKind2.CompoundStmt);

        // 参数类型：标量或指针（RawPtr），其余不支持。
        var paramTypes = new List<string>();
        var paramNames = new List<string>();
        var context = new FunctionContext();
        foreach (var child in children)
        {
            if ((ClangCursorKind)child.Kind != ClangCursorKind.ParmDecl)
            {
                continue;
            }

            var mapping = MapType(_api.GetCursorType(child));
            if (mapping == null)
            {
                SkipReason = $"parameter '{_api.GetString(_api.GetCursorSpelling(child))}' has unsupported type";
                return null;
            }

            paramTypes.Add(mapping.EidosType);
            var paramName = _api.GetString(_api.GetCursorSpelling(child));
            paramNames.Add(paramName);
            context.VarTypes[paramName] = mapping;
        }

        var returnMapping = MapType(_api.GetCursorResultType(function));
        if (returnMapping == null)
        {
            SkipReason = "return type is not a supported scalar or pointer";
            return null;
        }

        var returnType = returnMapping.EidosType;
        var bodyText = TranslateStatements(Children(body), context, state);
        if (bodyText == null)
        {
            return null;
        }

        var signature = paramTypes.Count == 0
            ? $"Unit -> {returnType}"
            : $"{string.Join(" -> ", paramTypes)} -> {returnType}";
        var binders = paramNames.Count == 0
            ? "_ =>"
            : string.Join(" => ", paramNames) + " =>";
        var tail = returnType == "Unit" ? "()" : "0";

        var sb = new StringBuilder();
        sb.AppendLine($"{_api.GetString(_api.GetCursorSpelling(function))} :: {signature}");
        sb.AppendLine("{");
        sb.AppendLine($"    {binders} {{");
        sb.AppendLine(Indent(bodyText, 8));
        sb.AppendLine($"        {tail}");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private string? TranslateStatements(List<ClangCursor> statements, FunctionContext context, TranslationState state)
    {
        var lines = new List<string>();
        foreach (var statement in statements)
        {
            var line = TranslateStatement(statement, context, state);
            if (line == null)
            {
                return null;
            }

            lines.Add(line);
        }

        return string.Join(Environment.NewLine, lines);
    }

    private string? TranslateStatement(ClangCursor statement, FunctionContext context, TranslationState state)
    {
        switch (statement.Kind)
        {
            case ClangCursorKind2.DeclStmt:
            {
                var lines = new List<string>();
                foreach (var varDecl in Children(statement))
                {
                    if ((ClangCursorKind)varDecl.Kind != ClangCursorKind.VarDecl)
                    {
                        SkipReason = "unsupported declaration in statement";
                        return null;
                    }

                    var varName = _api.GetString(_api.GetCursorSpelling(varDecl));
                    var varType = MapType(_api.GetCursorType(varDecl));
                    if (varType == null)
                    {
                        SkipReason = $"local '{varName}' has unsupported type";
                        return null;
                    }

                    var initChildren = Children(varDecl);
                    string? init;
                    if (initChildren.Count > 0)
                    {
                        init = TranslateExpression(initChildren[0], context, state);
                    }
                    else
                    {
                        init = DefaultZero(varType.EidosType);
                        if (varType.EidosType == "RawPtr")
                        {
                            state.NeedsFfiImport = true;
                        }
                    }

                    if (init == null)
                    {
                        return null;
                    }

                    context.VarTypes[varName] = varType;
                    lines.Add($"mut {varName} := {init};");
                }

                return string.Join(Environment.NewLine, lines);
            }

            case ClangCursorKind2.CompoundStmt:
            {
                var inner = TranslateStatements(Children(statement), context, state);
                return inner == null ? null : inner;
            }

            case ClangCursorKind2.ReturnStmt:
            {
                var valueChildren = Children(statement);
                if (valueChildren.Count == 0)
                {
                    return string.Empty;
                }

                var value = TranslateExpression(valueChildren[0], context, state);
                return value == null ? null : $"return {value};";
            }

            case ClangCursorKind2.IfStmt:
            {
                var parts = Children(statement);
                if (parts.Count is < 2 or > 3)
                {
                    SkipReason = "unsupported if form";
                    return null;
                }

                var condition = TranslateExpression(parts[0], context, state);
                if (condition == null)
                {
                    return null;
                }

                var thenBody = TranslateStatements(Children(parts[1]), context, state);
                if (thenBody == null)
                {
                    return null;
                }

                string Brace(string inner) =>
                    $"{{{Environment.NewLine}{Indent(inner, 8)}{Environment.NewLine}    (){Environment.NewLine}}}";

                if (parts.Count == 3)
                {
                    var elseBody = parts[2].Kind == ClangCursorKind2.IfStmt
                        ? TranslateStatement(parts[2], context, state)
                        : TranslateStatements(Children(parts[2]), context, state);
                    if (elseBody == null)
                    {
                        return null;
                    }

                    return $"if {condition} then{Brace(thenBody)} else{Brace(elseBody)};";
                }

                return $"if {condition} then{Brace(thenBody)} else {{ () }};";
            }

            case ClangCursorKind2.WhileStmt:
            {
                var parts = Children(statement);
                if (parts.Count != 2)
                {
                    SkipReason = "unsupported while form";
                    return null;
                }

                var condition = TranslateExpression(parts[0], context, state);
                if (condition == null)
                {
                    return null;
                }

                var body = TranslateStatements(Children(parts[1]), context, state);
                if (body == null)
                {
                    return null;
                }

                return $"loop {{{Environment.NewLine}    if !({condition}) then break;{Environment.NewLine}{Indent(body, 4)}{Environment.NewLine}}};";
            }

            case ClangCursorKind2.ForStmt:
            {
                // init / cond / inc / body 去糖为声明 + loop。
                var parts = Children(statement);
                if (parts.Count != 4)
                {
                    SkipReason = "unsupported for form";
                    return null;
                }

                var init = TranslateStatement(parts[0], context, state);
                if (init == null || string.IsNullOrEmpty(init))
                {
                    SkipReason = "unsupported for-init";
                    return null;
                }

                var condition = TranslateExpression(parts[1], context, state);
                if (condition == null)
                {
                    return null;
                }

                var increment = TranslateExpression(parts[2], context, state, asStatement: true);
                if (increment == null)
                {
                    return null;
                }

                var body = TranslateStatements(Children(parts[3]), context, state);
                if (body == null)
                {
                    return null;
                }

                var forSb = new StringBuilder();
                forSb.AppendLine(init);
                forSb.AppendLine("loop {");
                forSb.AppendLine($"    if !({condition}) then break;");
                forSb.AppendLine(Indent(body, 8));
                forSb.AppendLine($"    {increment};");
                forSb.AppendLine("    ()");
                forSb.AppendLine("}");
                return forSb.ToString();
            }

            default:
            {
                // 裸表达式语句（赋值/调用）。
                if (statement.Kind is ClangCursorKind2.BinaryOperator or ClangCursorKind2.CallExpr)
                {
                    return TranslateExpression(statement, context, state, asStatement: true) is { } expr
                        ? $"{expr};"
                        : null;
                }

                SkipReason = $"unsupported statement kind {statement.Kind}";
                return null;
            }
        }
    }

    private string? TranslateExpression(ClangCursor expression, FunctionContext context, TranslationState state, bool asStatement = false)
    {
        switch (expression.Kind)
        {
            case ClangCursorKind2.UnexposedExpr:
            {
                var inner = Children(expression);
                return inner.Count == 1 ? TranslateExpression(inner[0], context, state, asStatement) : null;
            }

            case ClangCursorKind2.CStyleCastExpr:
            {
                // 指针视角的转换（如 (void*)0）与同类标量转换按原样透传；
                // int/float 间的语义转换不支持。
                var castMapping = MapType(_api.GetCursorType(expression));
                var inner = Children(expression);
                if (inner.Count != 1 || castMapping == null)
                {
                    SkipReason = "unsupported cast";
                    return null;
                }

                var innerMapping = MapType(_api.GetCursorType(inner[0]));
                if (castMapping.EidosType != "RawPtr" &&
                    (innerMapping == null || innerMapping.EidosType != castMapping.EidosType))
                {
                    SkipReason = "unsupported value-changing cast";
                    return null;
                }

                return TranslateExpression(inner[0], context, state, asStatement);
            }

            case ClangCursorKind2.DeclRefExpr:
                return _api.GetString(_api.GetCursorSpelling(expression));

            case ClangCursorKind2.IntegerLiteral:
                return EvaluateLiteral(expression, integer: true);

            case ClangCursorKind2.FloatingLiteral:
                return EvaluateLiteral(expression, integer: false);

            case ClangCursorKind2.UnaryOperator:
                return TranslateUnaryOperator(expression, context, state);

            case ClangCursorKind2.MemberRefExpr:
                return TranslateMemberAccess(expression, context, state);

            case ClangCursorKind2.BinaryOperator:
            {
                var op = _api.GetString(_api.GetCursorSpelling(expression));
                var operands = Children(expression);
                if (operands.Count != 2)
                {
                    SkipReason = $"unsupported operand count for '{op}'";
                    return null;
                }

                if (op == "=")
                {
                    if (asStatement)
                    {
                        return TranslateAssignment(operands[0], operands[1], context, state);
                    }

                    SkipReason = "assignment used in expression context";
                    return null;
                }

                if (op is "==" or "!=" &&
                    (IsPointerTyped(operands[0]) || IsPointerTyped(operands[1])))
                {
                    return TranslatePointerComparison(op, operands[0], operands[1], context, state);
                }

                var left = TranslateExpression(operands[0], context, state);
                var right = TranslateExpression(operands[1], context, state);
                if (left == null || right == null)
                {
                    return null;
                }

                return op switch
                {
                    "+" or "-" or "*" or "/" or "%" or "<" or "<=" or ">" or ">=" or "==" or "!=" => $"{left} {op} {right}",
                    _ when op == "&&" => $"{left} && {right}",
                    _ when op == "||" => $"{left} || {right}",
                    _ => Skip(op),
                };

                string? Skip(string unsupported)
                {
                    SkipReason = $"unsupported operator '{unsupported}'";
                    return null;
                }
            }

            case ClangCursorKind2.CallExpr:
            {
                var operands = Children(expression);
                if (operands.Count == 0)
                {
                    SkipReason = "unsupported call form";
                    return null;
                }

                var callee = _api.GetString(_api.GetCursorSpelling(operands[0]));
                if (state.DefinedNames.Contains(callee))
                {
                    return TranslateCall(callee, operands.Skip(1), context, state);
                }

                return TranslateExternalCall(callee, operands.Skip(1), context, state);
            }

            default:
                SkipReason = $"unsupported expression kind {expression.Kind}";
                return null;
        }
    }

    private string? TranslateUnaryOperator(ClangCursor expression, FunctionContext context, TranslationState state)
    {
        var tokens = Tokenize(expression);
        var op = tokens.FirstOrDefault(static token => token.Kind == ClangTokenKind.Punctuation).Spelling;
        var operands = Children(expression);
        if (op == null || operands.Count != 1)
        {
            SkipReason = "unsupported unary operator";
            return null;
        }

        var operand = operands[0];
        if (op == "*")
        {
            if (!TryResolveBaseVariable(operand, context, out var varType) || varType.ElementEidosType == null)
            {
                SkipReason = "dereference of a pointer without a supported element type";
                return null;
            }

            var pointer = TranslateExpression(operand, context, state);
            return pointer == null
                ? null
                : $"Ffi.load[{varType.ElementEidosType}]({pointer})";
        }

        if (op == "!")
        {
            var operandText = TranslateExpression(operand, context, state);
            if (operandText == null)
            {
                return null;
            }

            if (IsPointerTyped(operand))
            {
                state.NeedsFfiImport = true;
                return $"Ffi.pointer_eq({operandText})(Ffi.null_pointer())";
            }

            return $"({operandText} == 0)";
        }

        if (op == "-")
        {
            var operandText = TranslateExpression(operand, context, state);
            return operandText == null ? null : $"-{operandText}";
        }

        SkipReason = $"unsupported unary operator '{op}'";
        return null;
    }

    private string? TranslateMemberAccess(ClangCursor expression, FunctionContext context, TranslationState state)
    {
        var member = _api.GetString(_api.GetCursorSpelling(expression));
        var operands = Children(expression);
        if (operands.Count != 1 ||
            !TryResolveBaseVariable(operands[0], context, out var varType) ||
            varType.RecordName == null)
        {
            SkipReason = "member access on a non-record-pointer base";
            return null;
        }

        var memberMapping = MapType(_api.GetCursorType(expression));
        if (memberMapping == null)
        {
            SkipReason = $"member '{member}' has an unsupported type";
            return null;
        }

        var pointer = TranslateExpression(operands[0], context, state);
        if (pointer == null)
        {
            return null;
        }

        var access = new RecordMemberAccess(
            varType.RecordSpelling!,
            varType.RecordName!,
            member,
            _api.GetString(_api.GetTypeSpelling(_api.GetCursorType(expression))),
            memberMapping.EidosType);
        state.RecordMembers[(varType.RecordName!, member)] = access;
        return $"c2e_{varType.RecordName}_{member}_get({pointer})";
    }

    private string? TranslateAssignment(ClangCursor target, ClangCursor value, FunctionContext context, TranslationState state)
    {
        // *p = v → Ffi.store[T](p)(v)；u->m = v → c2e_<R>_<m>_set(u)(v)；其余为普通赋值。
        if (target.Kind == ClangCursorKind2.UnaryOperator)
        {
            var tokens = Tokenize(target);
            var op = tokens.FirstOrDefault(static token => token.Kind == ClangTokenKind.Punctuation).Spelling;
            var targetOperands = Children(target);
            if (op != "*" || targetOperands.Count != 1 ||
                !TryResolveBaseVariable(targetOperands[0], context, out var varType) ||
                varType.ElementEidosType == null)
            {
                SkipReason = "unsupported assignment target dereference";
                return null;
            }

            var pointer = TranslateExpression(targetOperands[0], context, state);
            var assigned = TranslateExpression(value, context, state);
            if (pointer == null || assigned == null)
            {
                return null;
            }

            state.NeedsFfiImport = true;
            return $"Ffi.store[{varType.ElementEidosType}]({pointer})({assigned})";
        }

        if (target.Kind == ClangCursorKind2.MemberRefExpr)
        {
            var member = _api.GetString(_api.GetCursorSpelling(target));
            var targetOperands = Children(target);
            if (targetOperands.Count != 1 ||
                !TryResolveBaseVariable(targetOperands[0], context, out var varType) ||
                varType.RecordName == null)
            {
                SkipReason = "unsupported member assignment target";
                return null;
            }

            var memberMapping = MapType(_api.GetCursorType(target));
            if (memberMapping == null)
            {
                SkipReason = $"member '{member}' has an unsupported type";
                return null;
            }

            var pointer = TranslateExpression(targetOperands[0], context, state);
            var assigned = TranslateExpression(value, context, state);
            if (pointer == null || assigned == null)
            {
                return null;
            }

            state.RecordMembers[(varType.RecordName!, member)] = new RecordMemberAccess(
                varType.RecordSpelling!,
                varType.RecordName!,
                member,
                _api.GetString(_api.GetTypeSpelling(_api.GetCursorType(target))),
                memberMapping.EidosType);
            return $"c2e_{varType.RecordName}_{member}_set({pointer})({assigned})";
        }

        var targetText = TranslateExpression(target, context, state);
        var valueText = TranslateExpression(value, context, state);
        return targetText == null || valueText == null ? null : $"{targetText} := {valueText}";
    }

    private string? TranslatePointerComparison(
        string op,
        ClangCursor left,
        ClangCursor right,
        FunctionContext context,
        TranslationState state)
    {
        // 指针字面量（0 / (void*)0 形态的 NULL）翻成 null_pointer；其余按 pointer_eq 比较。
        string? TranslateOperand(ClangCursor operand)
        {
            switch (ClassifyPointerLiteral(operand))
            {
                case PointerLiteralKind.NullLiteral:
                    state.NeedsFfiImport = true;
                    return "Ffi.null_pointer()";
                case PointerLiteralKind.NonNullLiteral:
                    SkipReason = "non-null integer used as a pointer value";
                    return null;
                default:
                    return TranslateExpression(operand, context, state);
            }
        }

        var leftText = TranslateOperand(left);
        var rightText = TranslateOperand(right);
        if (leftText == null || rightText == null)
        {
            return null;
        }

        state.NeedsFfiImport = true;
        var equality = $"Ffi.pointer_eq({leftText})({rightText})";
        return op == "!=" ? $"!({equality})" : equality;
    }

    /// <summary>占位映射：调用实参强转查询失败时按普通标量处理。</summary>
    private static readonly CTypeMapping UnsupportedMapping = new("Int", null, null, null);

    private string? TranslateCall(string callee, IEnumerable<ClangCursor> arguments, FunctionContext context, TranslationState state)
    {
        var parameterMappings = state.FunctionParameters.TryGetValue(callee, out var mappings)
            ? mappings
            : [];
        var argumentList = arguments.ToList();
        var argumentTexts = new List<string>();
        for (var i = 0; i < argumentList.Count; i++)
        {
            var translated = TranslateCallArgument(
                argumentList[i],
                i < parameterMappings.Count ? parameterMappings[i] : null,
                context,
                state);
            if (translated == null)
            {
                return null;
            }

            argumentTexts.Add(translated);
        }

        return $"{callee}({string.Join(", ", argumentTexts)})";
    }

    /// <summary>调用实参翻译：指针参数位置的 0/(T*)0 视为 NULL 字面量。</summary>
    private string? TranslateCallArgument(ClangCursor argument, CTypeMapping? parameter, FunctionContext context, TranslationState state)
    {
        if (parameter?.EidosType == "RawPtr")
        {
            switch (ClassifyPointerLiteral(argument))
            {
                case PointerLiteralKind.NullLiteral:
                    state.NeedsFfiImport = true;
                    return "Ffi.null_pointer()";
                case PointerLiteralKind.NonNullLiteral:
                    SkipReason = "non-null integer used as a pointer value";
                    return null;
            }
        }

        return TranslateExpression(argument, context, state);
    }

    private string? TranslateExternalCall(string callee, IEnumerable<ClangCursor> arguments, FunctionContext context, TranslationState state)
    {
        if (!state.DeclaredFunctions.TryGetValue(callee, out var declaration) ||
            _api.CursorIsVariadic(declaration) != 0)
        {
            SkipReason = $"call to untranslated function '{callee}'";
            return null;
        }

        var functionType = _api.GetCursorType(declaration);
        var arity = _api.GetNumArgTypes(functionType);
        var argumentList = arguments.ToList();
        if (arity != argumentList.Count)
        {
            SkipReason = $"call to '{callee}' does not match its declaration";
            return null;
        }

        var parameterMappings = new List<CTypeMapping>((int)arity);
        for (var i = 0; i < arity; i++)
        {
            var mapping = MapType(_api.GetArgType(functionType, (uint)i));
            if (mapping == null)
            {
                SkipReason = $"parameter {i + 1} of '{callee}' has an unsupported type";
                return null;
            }

            parameterMappings.Add(mapping);
        }

        var returnMapping = MapType(_api.GetResultType(functionType));
        if (returnMapping == null)
        {
            SkipReason = $"return type of '{callee}' is not a supported scalar or pointer";
            return null;
        }

        if (!state.PendingExterns.TryGetValue(callee, out var pending))
        {
            pending = new PendingExtern(
                callee,
                $"c2e_ext_{callee}",
                parameterMappings.Select(static mapping => mapping.EidosType).ToList(),
                returnMapping.EidosType);
            state.PendingExterns[callee] = pending;
        }

        var argumentTexts = new List<string>(argumentList.Count);
        for (var i = 0; i < argumentList.Count; i++)
        {
            var translated = TranslateCallArgument(argumentList[i], parameterMappings[i], context, state);
            if (translated == null)
            {
                return null;
            }

            argumentTexts.Add(translated);
        }

        return $"{pending.EidosName}({string.Join(", ", argumentTexts)})";
    }

    private bool IsPointerTyped(ClangCursor operand) =>
        (ClangTypeKind)_api.GetCanonicalType(_api.GetCursorType(operand)).Kind == ClangTypeKind.Pointer;

    private enum PointerLiteralKind
    {
        NotLiteral,
        NullLiteral,
        NonNullLiteral
    }

    /// <summary>识别出现在指针位置的 0 / (T*)0（NULL）与非零整数字面量。</summary>
    private PointerLiteralKind ClassifyPointerLiteral(ClangCursor operand)
    {
        if (!IsPointerLiteral(operand))
        {
            return PointerLiteralKind.NotLiteral;
        }

        var current = operand;
        while (current.Kind != ClangCursorKind2.IntegerLiteral)
        {
            var inner = Children(current);
            if (inner.Count != 1)
            {
                return PointerLiteralKind.NotLiteral;
            }

            current = inner[0];
        }

        var result = _api.CursorEvaluate(current);
        if (result == IntPtr.Zero)
        {
            return PointerLiteralKind.NotLiteral;
        }

        try
        {
            return _api.EvalResultGetAsLongLong(result) == 0
                ? PointerLiteralKind.NullLiteral
                : PointerLiteralKind.NonNullLiteral;
        }
        finally
        {
            _api.EvalResultDispose(result);
        }
    }

    /// <summary>结构判定：cursor 是否为指针位置的整数字面量（含转换/包裹）。</summary>
    private bool IsPointerLiteral(ClangCursor operand)
    {
        if (!IsPointerTyped(operand))
        {
            return false;
        }

        var current = operand;
        while (true)
        {
            if (current.Kind == ClangCursorKind2.IntegerLiteral)
            {
                return true;
            }

            if (current.Kind is ClangCursorKind2.UnexposedExpr or ClangCursorKind2.CStyleCastExpr)
            {
                var inner = Children(current);
                if (inner.Count != 1)
                {
                    return false;
                }

                current = inner[0];
                continue;
            }

            return false;
        }
    }

    /// <summary>把（可能被 Unexposed/转换包裹的）表达式解析到已声明变量，取其类型信息。</summary>
    private bool TryResolveBaseVariable(ClangCursor operand, FunctionContext context, out CTypeMapping mapping)
    {
        mapping = null!;
        var current = operand;
        while (true)
        {
            if (current.Kind == ClangCursorKind2.DeclRefExpr)
            {
                var name = _api.GetString(_api.GetCursorSpelling(current));
                if (context.VarTypes.TryGetValue(name, out mapping!))
                {
                    return true;
                }

                return false;
            }

            if (current.Kind is ClangCursorKind2.UnexposedExpr or ClangCursorKind2.CStyleCastExpr)
            {
                var inner = Children(current);
                if (inner.Count != 1)
                {
                    return false;
                }

                current = inner[0];
                continue;
            }

            return false;
        }
    }

    private string? EvaluateLiteral(ClangCursor literal, bool integer)
    {
        var result = _api.CursorEvaluate(literal);
        if (result == IntPtr.Zero)
        {
            SkipReason = "literal evaluation failed";
            return null;
        }

        try
        {
            var kind = _api.EvalResultGetKind(result);
            if (integer)
            {
                return _api.EvalResultGetAsLongLong(result).ToString();
            }

            // 浮点字面量：EvalResult 文本形式即十进制字面量。
            var text = _api.EvalResultGetAsStr(result);
            var ptr = text == IntPtr.Zero ? string.Empty : System.Runtime.InteropServices.Marshal.PtrToStringUTF8(text) ?? string.Empty;
            return string.IsNullOrWhiteSpace(text == IntPtr.Zero ? string.Empty : ptr) ? null : NormalizeFloat(ptr);
        }
        finally
        {
            _api.EvalResultDispose(result);
        }
    }

    private static string NormalizeFloat(string text)
    {
        if (text.Contains('e') || text.Contains('E') || text.Contains('.'))
        {
            return text;
        }

        return text + ".0";
    }

    private static string DefaultZero(string eidosType) => eidosType switch
    {
        "Float" => "0.0",
        "RawPtr" => "Ffi.null_pointer()",
        _ => "0"
    };

    /// <summary>标量与指针的 Eidos 类型映射；指针额外携带元素类型 / 记录（union、struct）事实。</summary>
    private sealed record CTypeMapping(string EidosType, string? ElementEidosType, string? RecordSpelling, string? RecordName);

    private CTypeMapping? MapType(ClangType type)
    {
        var canonical = _api.GetCanonicalType(type);
        switch ((ClangTypeKind)canonical.Kind)
        {
            case ClangTypeKind.Void:
                return new CTypeMapping("Unit", null, null, null);
            case ClangTypeKind.Int or ClangTypeKind.Long or ClangTypeKind.LongLong or
                ClangTypeKind.Short or ClangTypeKind.CharS or ClangTypeKind.SChar or
                ClangTypeKind.UInt or ClangTypeKind.ULong or ClangTypeKind.ULongLong or
                ClangTypeKind.UShort or ClangTypeKind.UChar or ClangTypeKind.CharU or
                ClangTypeKind.Bool or ClangTypeKind.Enum:
                return new CTypeMapping("Int", null, null, null);
            case ClangTypeKind.Float or ClangTypeKind.Double:
                return new CTypeMapping("Float", null, null, null);
            case ClangTypeKind.Pointer:
                return MapPointerType(canonical);
            default:
                return null;
        }
    }

    private CTypeMapping? MapPointerType(ClangType canonicalPointer)
    {
        var pointee = _api.GetCanonicalType(_api.GetPointeeType(canonicalPointer));
        switch ((ClangTypeKind)pointee.Kind)
        {
            case ClangTypeKind.Int or ClangTypeKind.Long or ClangTypeKind.LongLong or
                ClangTypeKind.Short or ClangTypeKind.CharS or ClangTypeKind.SChar or
                ClangTypeKind.UInt or ClangTypeKind.ULong or ClangTypeKind.ULongLong or
                ClangTypeKind.UShort or ClangTypeKind.UChar or ClangTypeKind.CharU or
                ClangTypeKind.Bool or ClangTypeKind.Enum:
                return new CTypeMapping("RawPtr", "Int", null, null);
            case ClangTypeKind.Float or ClangTypeKind.Double:
                return new CTypeMapping("RawPtr", "Float", null, null);
            case ClangTypeKind.Record:
            {
                var spelling = _api.GetString(_api.GetTypeSpelling(pointee));
                var separator = spelling.IndexOf(' ');
                var recordName = separator > 0 ? spelling[(separator + 1)..] : spelling;
                if (string.IsNullOrWhiteSpace(recordName))
                {
                    return null;
                }

                return new CTypeMapping("RawPtr", null, spelling, recordName);
            }
            default:
                // void*、多级指针等：可传递比较，不可解引用。
                return new CTypeMapping("RawPtr", null, null, null);
        }
    }

    private List<(ClangTokenKind Kind, string Spelling)> Tokenize(ClangCursor cursor) =>
        _session?.TokenizeCursor(cursor).ToList() ?? [];

    private List<ClangCursor> Children(ClangCursor cursor)
    {
        var children = new List<ClangCursor>();
        _api.VisitChildren(cursor, (child, _, _) =>
        {
            children.Add(child);
            return ClangChildVisitResult.Continue;
        }, IntPtr.Zero);
        return children;
    }

    private static string Indent(string text, int width)
    {
        var pad = new string(' ', width);
        return string.Join(Environment.NewLine, text
            .Split(["\r\n", "\n"], StringSplitOptions.None)
            .Select(line => line.Length == 0 ? line : pad + line));
    }

    private sealed class FunctionContext
    {
        public Dictionary<string, CTypeMapping> VarTypes { get; } = new(StringComparer.Ordinal);
    }

    private sealed class TranslationState(
        IReadOnlySet<string> definedNames,
        IReadOnlyDictionary<string, ClangCursor> declaredFunctions)
    {
        public IReadOnlySet<string> DefinedNames { get; } = definedNames;
        public IReadOnlyDictionary<string, ClangCursor> DeclaredFunctions { get; } = declaredFunctions;
        public Dictionary<string, IReadOnlyList<CTypeMapping>> FunctionParameters { get; } = new(StringComparer.Ordinal);
        public Dictionary<string, PendingExtern> PendingExterns { get; } = new(StringComparer.Ordinal);
        public Dictionary<(string Record, string Member), RecordMemberAccess> RecordMembers { get; } = new();
        public bool NeedsFfiImport { get; set; }
    }
}

/// <summary>
/// 语句/表达式 cursor kind（clang 22 实测值，与声明段枚举分离维护）。
/// </summary>
internal static class ClangCursorKind2
{
    internal const int UnexposedExpr = 100;
    internal const int DeclRefExpr = 101;
    internal const int MemberRefExpr = 102;
    internal const int CallExpr = 103;
    internal const int IntegerLiteral = 106;
    internal const int FloatingLiteral = 107;
    internal const int UnaryOperator = 112;
    internal const int BinaryOperator = 114;
    internal const int CStyleCastExpr = 117;
    internal const int CompoundStmt = 202;
    internal const int IfStmt = 205;
    internal const int WhileStmt = 207;
    internal const int ForStmt = 209;
    internal const int ReturnStmt = 214;
    internal const int DeclStmt = 231;
}
